Bug fixes

diff --git a/.github/workflows/image-pull-and-tag.yaml b/.github/workflows/image-pull-and-tag.yaml
--- a/.github/workflows/image-pull-and-tag.yaml
+++ b/.github/workflows/image-pull-and-tag.yaml
@@ -1,4 +1,4 @@
-name: Retag Images to GHCR
+name: Retag and Build Images to GHCR
 
 on:
   push:
@@ -8,56 +8,65 @@ on:
       - '.original-images.yaml'
   workflow_dispatch:
 
+env:
+  REGISTRY: ghcr.io
+  IMAGE_NAME: ${{ github.repository }}
+
 jobs:
   retag-images:
     runs-on: ubuntu-latest
 
+    strategy:
+      fail-fast: false
+      max-parallel: 3
+      matrix:
+        image: []
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Set up Docker
-      uses: docker/setup-buildx-action@v2
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
 
-    - name: Log in to the Container registry
-      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Log in to the Container registry
+        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Read and retag images
-      run: |
-        if [ ! -f .original-images.yaml ]; then
-          echo "File .original-images.yaml not found!"
-          exit 1
-        fi
+      - name: Read images from file and set matrix
+        id: read-images
+        run: |
+          if [ ! -f .original-images.yaml ]; then
+            echo "File .original-images.yaml not found!"
+            exit 1
+          fi
 
-        # Read images from the YAML file
-        images=$(cat .original-images.yaml | yq '.[]')
+          echo "Reading images from .original-images.yaml"
+          images=$(yq '.[]' .original-images.yaml)
+          json_matrix=$(echo "$images" | jq -R -s -c 'split("\n") | map(select(length > 0) | split(":") | {path: .[0], tag: .[1]})')
+          echo "matrix=$json_matrix" >> $GITHUB_ENV
 
-        for image in $images; do
-          echo "Processing $image"
+      - name: Dynamically update matrix
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const matrix = JSON.parse(process.env.matrix);
+            return { matrix };
 
-          # Extract image name and tag
-          base_image=$(echo $image | cut -d ':' -f 1)
-          tag=$(echo $image | cut -d ':' -f 2)
-          
-          # Pull the original image
-          docker pull $image
+      - name: Build, retag, and push Docker images
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$(basename ${{ matrix.image.path }}):${{ matrix.image.tag }}
+          build-args: |
+            BASE_IMAGE=${{ matrix.image.path }}
+            BASE_TAG=${{ matrix.image.tag }}
 
-          # Retag to GHCR
-          new_image="ghcr.io/rackerlabs/$base_image:$tag"
-          docker tag $image $new_image
-
-          # Push to GHCR
-          docker push $new_image
-        done
-
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Logout from Docker
-      run: |
-        docker logout ghcr.io
+      - name: Logout from Docker
+        run: docker logout ${{ env.REGISTRY }}
 
